id = "harsh"
name = "Harsh"
version = "0.1.0"
schema_version = 1
authors = ["Bahiminin Benoit Dah"]
description = "Harsh. Rust without the braces."
repository = "https://github.com/Harsh-Programming-Language/zed-harsh"

[grammars.harsh]
repository = "https://github.com/Harsh-Programming-Language/tree-sitter-harsh"
rev = "REPLACE_WITH_COMMIT_SHA"

[language_servers.hrs-lsp]
name = "hrs-lsp"
languages = ["Harsh"]
