// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Emitter.
//!
//! Walks the block tree and writes Rust. Every token is either copied verbatim
//! or substituted locally; nothing is reconstructed from a semantic tree. The
//! whitespace *between* tokens is copied straight out of the original source,
//! which is why multi-line method chains keep their shape in the output and why
//! the source map is close to an identity mapping.

use crate::layout::{Block, BlockKind, Group, Line, Node};
use crate::lex::{Tk, Token};
use crate::juxt::{self, Jx};
use crate::rules::{ALWAYS_SEMI, BLOCK_NEEDS_SEMI};

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Fix {
    /// Drop this token.
    Skip,
    /// Replace this token with fixed text.
    Text(&'static str),
    /// Write `(` before this token.
    Open,
    /// Write `)` after this token.
    CloseAfter,
    /// Both: a one-token bare parameter, `fn f self`.
    Wrap,
    /// Write this token, then fixed text after it.
    TextAfter(&'static str),
}

pub struct MapEntry {
    pub gen_lo: u32,
    pub gen_hi: u32,
    pub src_lo: u32,
    pub src_hi: u32,
}

pub struct Emitter<'a> {
    /// Closing parens owed after a block's `}`, because the block *is* the
    /// closure body that the argument list encloses.
    pending_close: usize,
    stmt_ctx: bool,
    /// The kind of block whose nodes are being written.
    kind: BlockKind,
    /// The enclosing block was opened by a macro call: its last entry takes
    /// no trailing separator (2026-09-17).
    macro_lit: bool,
    /// The next `indent()` writes nothing: a fragment that begins mid-line.
    skip_indent: bool,
    /// The last token was an include macro's bang: the string that follows
    /// is a path to re-base.
    include_path_pending: bool,
    /// Fixups to use for the next line instead of the computed ones.
    forced_jx: Option<Vec<(usize, juxt::Jx)>>,
    /// A token index to skip when the next line is written: a header's
    /// optional `(`.
    forced_skip: Option<usize>,
    /// See `set_include_base`.
    include_base: Option<String>,
    src: &'a str,
    pub out: String,
    pub map: Vec<MapEntry>,
    level: usize,
}


impl<'a> Emitter<'a> {
    pub fn new(src: &'a str) -> Self {
        Emitter {
            macro_lit: false,
            pending_close: 0,
            stmt_ctx: false,
            kind: BlockKind::Items,
            skip_indent: false,
            include_path_pending: false,
            include_base: None,
            forced_jx: None,
            forced_skip: None,
            src,
            out: String::new(),
            map: Vec::new(),
            level: 0,
        }
    }

    fn here(&self) -> u32 {
        self.out.len() as u32
    }

    fn indent(&mut self) {
        if std::mem::take(&mut self.skip_indent) {
            return;
        }
        for _ in 0..self.level {
            self.out.push_str("    ");
        }
    }

    /// The source whitespace between two tokens, as `tok` would copy it: a
    /// line break becomes a break plus this level's indent plus the source
    /// line's own indentation.
    fn gap(&mut self, prev_hi: u32, lo: u32) {
        if lo <= prev_hi {
            return;
        }
        let gap = &self.src[prev_hi as usize..lo as usize];
        if gap.contains('\n') {
            let tail = gap.rsplit('\n').next().unwrap_or("");
            self.out.push('\n');
            for _ in 0..self.level {
                self.out.push_str("    ");
            }
            self.out.push_str(tail);
        } else {
            self.out.push_str(gap);
        }
    }

    /// Emit a token, recording the mapping from its generated bytes back to its
    /// hrs bytes.
    fn tok(&mut self, t: &Token, prev: Option<&Token>, turbofish: bool, brace: bool) {
        // `<-` becomes `.`, which binds tight on both sides, so the spaces the
        // user wrote around the arrow are dropped. A line break is kept, since
        // that is the multi-line chain style.
        let tight = t.kind == Tk::LArrow || prev.map(|p| p.kind == Tk::LArrow).unwrap_or(false);
        // Generated Rust follows Rust's spacing: a call paren sits against its
        // callee -- `map(`, `iter()`, `Some(x)`, `format!(` -- whatever gap
        // the `.hrs` has, which keeps its own idiom. Keyword parens keep
        // their space (`if (a)`, `return (x)`), as rustfmt writes them.
        let tight = tight
            || (t.kind == Tk::Open('(')
                && prev.map_or(false, |p| match p.kind {
                    Tk::Ident => !crate::rules::is_keyword(&p.text),
                    Tk::Close(')') | Tk::Close(']') | Tk::Gt => true,
                    Tk::Punct => p.text == "!" || p.text == "?",
                    _ => false,
                }));
        // A synthetic token's span no longer says where it sits, so source
        // whitespace around it must not be copied. A single space is written
        // when one is needed to keep words apart.
        if t.synthetic {
            // A synthetic paren is tight against a name or a closing bracket,
            // but not against an operator: `let v = (f(x))`, not `let v =(f(x))`.
            let last = self.out.chars().last();
            let after_value = matches!(last, Some(c)
                if c.is_alphanumeric() || c == '_' || c == ')' || c == ']' || c == '>' || c == '!');
            // `.` and `::` bind tight on both sides, synthetic or not.
            let path = |k: &Tk| matches!(k, Tk::LArrow | Tk::Dot | Tk::PathSep);
            let arrow = path(&t.kind) || prev.map_or(false, |p| path(&p.kind));
            // Rust's spacing for the punctuation an expansion brings with it:
            // `,` and `;` sit against what precedes them, a closing bracket
            // against its content, and nothing is written after an opener.
            let punct = matches!(t.kind, Tk::Comma | Tk::Semi | Tk::Close(_));
            let after_open = self.out.ends_with('[') || self.out.ends_with('{');
            let tight = arrow
                || punct
                || after_open
                || (matches!(t.kind, Tk::Open('(') | Tk::Close(')')) && after_value)
                || (t.kind == Tk::Open('[') && after_value);
            if !tight
                && !self.out.ends_with(' ')
                && !self.out.ends_with('\n')
                && !self.out.ends_with('(')
                && !self.out.is_empty()
            {
                self.out.push(' ');
            }
            let lo = self.here();
            // A synthetic token is still Harsh: an expansion's `<-` becomes a
            // `.` and its `.` a `::`, exactly as a hand-written one does.
            match t.kind {
                Tk::Dot => self.out.push_str("::"),
                Tk::LArrow => self.out.push('.'),
                _ => self.out.push_str(&t.text),
            }
            let hi = self.here();
            self.map.push(MapEntry {
                gen_lo: lo,
                gen_hi: hi,
                src_lo: t.span.lo,
                src_hi: t.span.hi,
            });
            return;
        }
        // Copy the original inter-token whitespace, so line breaks inside a
        // logical line survive into the output.
        // A pipe's synthetic tokens have no position (zero-width spans); the
        // `()` that `$` becomes keeps the `$`'s span and so keeps its gaps.
        if let Some(p) = prev.filter(|p| !p.synthetic || p.dollar) {
            if t.span.lo > p.span.hi {
                let gap = &self.src[p.span.hi as usize..t.span.lo as usize];
                if gap.contains('\n') {
                    let tail = gap.rsplit('\n').next().unwrap_or("");
                    self.out.push('\n');
                    for _ in 0..self.level {
                        self.out.push_str("    ");
                    }
                    self.out.push_str(tail);
                } else if !tight && (!gap.trim().is_empty() || !self.out.ends_with(' ')) {
                    // Never stack whitespace: a dropped group leaves a gap on
                    // both sides of where it used to be.
                    self.out.push_str(gap);
                }
            }
        }
        let lo = self.here();
        if turbofish {
            self.out.push_str("::");
        }
        match t.kind {
            Tk::Dot if brace => self.out.push_str("::{"),
            Tk::Dot => self.out.push_str("::"),
            Tk::LArrow => self.out.push('.'),
            Tk::Open('(') if brace => {}
            Tk::Close(')') if brace => self.out.push('}'),
            // The path of an `include_str!` / `include_bytes!` / `include!`
            // is relative to the file that contains it. The generated Rust
            // lives elsewhere, so the path is re-based on the way through.
            Tk::Str if self.include_path_pending => {
                let rebased = self.rebase_include(&t.text);
                self.out.push_str(&rebased);
            }
            _ => self.out.push_str(&t.text),
        }
        self.include_path_pending = t.kind == Tk::Punct
            && t.text == "!"
            && prev.map_or(false, |p| p.kind == Tk::Ident && matches!(p.text.as_str(), "include_str" | "include_bytes" | "include"));
        let hi = self.here();
        self.map.push(MapEntry {
            gen_lo: lo,
            gen_hi: hi,
            src_lo: t.span.lo,
            src_hi: t.span.hi,
        });
    }

    /// Where the generated file stands relative to the source: the
    /// directory prefix that puts an include path right again. Set by the
    /// driver; unset for a single file written beside its source.
    pub fn set_include_base(&mut self, from_dir: &std::path::Path, out_dir: &std::path::Path) {
        self.include_base = relative_dir(out_dir, from_dir);
    }

    fn rebase_include(&self, lit: &str) -> String {
        let Some(base) = self.include_base.as_ref() else { return lit.to_string() };
        // Only a plain, relative string literal is re-based.
        if !lit.starts_with('"') || lit.len() < 2 || lit.starts_with("\"/") {
            return lit.to_string();
        }
        let inner = &lit[1..lit.len() - 1];
        let joined = normalize_path(&format!("{}/{}", base, inner));
        format!("\"{}\"", joined)
    }

    /// True when `toks[i]` begins a generic argument list that is immediately
    /// followed by the path separator, i.e. `Vec<i32>.new()`. Such a list must
    /// be emitted as a turbofish, because `Vec<i32>::new()` is a parse error in
    /// expression position. Turbofish is legal in type position too, so this
    /// substitution is safe without knowing which position we are in.
    fn needs_turbofish(toks: &[Token], i: usize) -> bool {
        if toks.get(i).map(|t| t.kind != Tk::Lt).unwrap_or(true) {
            return false;
        }
        match toks.get(i.wrapping_sub(1)).map(|t| &t.kind) {
            Some(Tk::Ident) => {}
            _ => return false,
        }
        // `fn name<T> (..)` and `struct Name<T>` are definitions, where the
        // generics are declared rather than applied. Turbofish is illegal there.
        if i >= 2 {
            if let Some(k) = toks.get(i - 2) {
                if k.kind == Tk::Ident
                    && matches!(
                        k.text.as_str(),
                        "fn" | "struct" | "enum" | "union" | "trait" | "type" | "impl"
                    )
                {
                    return false;
                }
            }
        }
        let mut depth = 0i32;
        for (k, t) in toks.iter().enumerate().skip(i) {
            match t.kind {
                Tk::Lt => depth += 1,
                Tk::Gt => {
                    depth -= 1;
                    if depth == 0 {
                        return matches!(
                            toks.get(k + 1).map(|t| &t.kind),
                            Some(Tk::Dot) | Some(Tk::Open('('))
                        );
                    }
                }
                // `>>` closes two lists at once: `collect<Vec<_>> ()`.
                Tk::Punct if t.text == ">>" => {
                    depth -= 2;
                    if depth <= 0 {
                        return depth == 0
                            && matches!(
                                toks.get(k + 1).map(|t| &t.kind),
                                Some(Tk::Dot) | Some(Tk::Open('('))
                            );
                    }
                }
                // Anything that cannot appear inside a generic argument list
                // means this `<` was a comparison after all.
                Tk::Semi | Tk::Open('{') | Tk::Close('}') | Tk::FatArrow => return false,
                _ => {}
            }
        }
        false
    }

    /// `.(` opens a use-tree group and must become `::{`, with its matching
    /// `)` becoming `}`. `.(` is not valid Rust in any other position, so this
    /// is safe to apply globally without knowing we are inside a `use`.
    fn brace_groups(toks: &[Token]) -> std::collections::HashSet<usize> {
        let mut out = std::collections::HashSet::new();
        let mut stack: Vec<bool> = Vec::new();
        for (i, t) in toks.iter().enumerate() {
            match t.kind {
                Tk::Open('(') => {
                    let is_group = i > 0 && toks[i - 1].kind == Tk::Dot;
                    if is_group {
                        out.insert(i);
                        out.insert(i - 1);
                    }
                    stack.push(is_group);
                }
                Tk::Open(_) => stack.push(false),
                Tk::Close(')') => {
                    if stack.pop() == Some(true) {
                        out.insert(i);
                    }
                }
                Tk::Close(_) => {
                    stack.pop();
                }
                _ => {}
            }
        }
        out
    }

    /// Curried parameter groups.
    ///
    /// The parameter region of a `fn` header is bounded -- it runs from after
    /// the name (and any generics) to the `->` or the block-opening `:`. Inside
    /// that region the rewrite is purely local, so no expression parsing is
    /// needed:
    ///
    /// ```text
    /// (a: T) (b: U)  ->  (a: T, b: U)
    /// name: &str     ->  (name: &str)
    /// ()             ->  ()          (already a Rust empty list)
    /// ```
    ///
    /// A comma inside a group never reaches here: `layout::check_fn_params`
    /// rejects it, so one group is always one parameter.
    fn param_fixups(toks: &[Token]) -> std::collections::HashMap<usize, Fix> {
        use std::collections::HashMap;
        let mut out: HashMap<usize, Fix> = HashMap::new();

        // Locate a top-level `fn` and the name after it.
        let mut d = 0i32;
        let mut fk = None;
        for (i, t) in toks.iter().enumerate() {
            match t.kind {
                Tk::Open(_) => d += 1,
                Tk::Close(_) => d -= 1,
                Tk::Ident if d == 0 && t.text == "fn" => {
                    fk = Some(i);
                    break;
                }
                _ => {}
            }
        }
        let Some(fk) = fk else { return out };
        let mut i = fk + 1;
        if toks.get(i).map(|t| t.kind != Tk::Ident).unwrap_or(true) {
            return out;
        }
        i += 1;
        // Skip a generic parameter declaration.
        if toks.get(i).map(|t| t.kind == Tk::Lt).unwrap_or(false) {
            let mut gd = 0i32;
            while i < toks.len() {
                match toks[i].kind {
                    Tk::Lt => gd += 1,
                    Tk::Gt => {
                        gd -= 1;
                        if gd == 0 {
                            i += 1;
                            break;
                        }
                    }
                    _ => {}
                }
                i += 1;
            }
        }
        // A doc comment or an attribute may precede the first group, on its
        // own line: a documented parameter.
        let after_name = i;
        while i < toks.len() && toks[i].is_comment() {
            i += 1;
        }
        let start = i;
        if start >= toks.len() {
            return out;
        }

        // The region ends at a top-level `->`. A `:` only ends it when it is
        // the block opener at the end of the line -- `name: &str` has one too.
        let mut end = toks.len();
        let mut d = 0i32;
        for k in start..toks.len() {
            match toks[k].kind {
                // A `[where …]` clause ends the parameters as `->` does.
                Tk::Open('[') if d == 0 && toks.get(k + 1).map_or(false, |t| t.is_kw("where")) => {
                    end = k;
                    break;
                }
                Tk::Open(_) => d += 1,
                Tk::Close(_) => d -= 1,
                Tk::Punct if d == 0 && toks[k].text == "->" => {
                    end = k;
                    break;
                }
                _ => {}
            }
        }
        if end == toks.len() {
            // No return type: the region ends at the block-opening colon.
            end = toks
                .iter()
                .rposition(|t| t.kind == Tk::Colon)
                .unwrap_or(toks.len());
        }
        if start >= end {
            return out;
        }

        if toks[start].kind == Tk::Open('(') {
            // Paren form: collect the top-level groups in the region.
            let mut groups: Vec<(usize, usize)> = Vec::new();
            let mut k = start;
            while k < end {
                if toks[k].kind == Tk::Open('(') {
                    let open = k;
                    let mut gd = 0i32;
                    let mut close = None;
                    while k < end {
                        match toks[k].kind {
                            Tk::Open('(') => gd += 1,
                            Tk::Close(')') => {
                                gd -= 1;
                                if gd == 0 {
                                    close = Some(k);
                                    break;
                                }
                            }
                            _ => {}
                        }
                        k += 1;
                    }
                    match close {
                        Some(c) => groups.push((open, c)),
                        None => return out,
                    }
                }
                k += 1;
            }
            if groups.len() < 2 {
                return out;
            }
            // An empty group among others is a unit placeholder and vanishes.
            let kept: Vec<(usize, usize)> =
                groups.iter().copied().filter(|(o, c)| c - o > 1).collect();
            for (o, c) in &groups {
                if c - o <= 1 {
                    out.insert(*o, Fix::Skip);
                    out.insert(*c, Fix::Skip);
                }
            }
            if kept.is_empty() {
                // Every group was empty: keep the first pair.
                let (o, c) = groups[0];
                out.remove(&o);
                out.remove(&c);
                return out;
            }
            for (n, (o, c)) in kept.iter().enumerate() {
                if n > 0 {
                    out.insert(*o, Fix::Skip);
                }
                if n + 1 < kept.len() {
                    out.insert(*c, Fix::Text(","));
                }
            }
            // A documented first parameter: its doc comment precedes the
            // first group, but Rust wants the `(` before any parameter's
            // doc, so the paren opens at the first comment instead.
            if let Some(&(o, _)) = kept.first() {
                let first_comment = (after_name..o).find(|&k| toks[k].is_comment());
                if let Some(fc) = first_comment {
                    out.insert(o, Fix::Skip);
                    out.insert(fc, Fix::Open);
                }
            }
        } else {
            // Bare form: `fn greet name: &str -> String:`. A single token,
            // `fn f self`, takes both fixes at once.
            if start == end - 1 {
                out.insert(start, Fix::Wrap);
            } else {
                out.insert(start, Fix::Open);
                out.insert(end - 1, Fix::CloseAfter);
            }
        }
        out
    }

    /// `[where T: Clone + Send]` -- the brackets suppress layout, so the `:` in
    /// the bound cannot be mistaken for a block opener. They are stripped on
    /// emission.
    fn where_fixups(toks: &[Token], out: &mut std::collections::HashMap<usize, Fix>) {
        for i in 0..toks.len() {
            if toks[i].kind != Tk::Open('[') || !toks.get(i + 1).map(|t| t.is_kw("where")).unwrap_or(false) {
                continue;
            }
            let mut d = 0i32;
            for k in i..toks.len() {
                match toks[k].kind {
                    Tk::Open('[') => d += 1,
                    Tk::Close(']') => {
                        d -= 1;
                        if d == 0 {
                            out.insert(i, Fix::Skip);
                            out.insert(k, Fix::Skip);
                            return;
                        }
                    }
                    _ => {}
                }
            }
        }
    }

    /// Rust forbids a struct literal in a `match` scrutinee or an `if`/`while`
    /// condition, because it cannot tell the literal's brace from the block's.
    /// Harsh has no such ambiguity -- the `:` ends the expression -- so the
    /// scrutinee is parenthesised on emission to keep the output legal.
    fn scrutinee_fixups(toks: &[Token], out: &mut std::collections::HashMap<usize, Fix>) {
        let sig: Vec<usize> = (0..toks.len()).filter(|&i| !toks[i].is_comment()).collect();
        let Some(&end) = sig.last() else { return };
        if toks[end].kind != Tk::Colon {
            return;
        }
        // Find the keyword that introduces the expression, and where it starts.
        let mut start = None;
        let mut d = 0i32;
        for &i in &sig {
            match toks[i].kind {
                Tk::Open(_) => d += 1,
                Tk::Close(_) => d -= 1,
                Tk::Ident if d == 0 => {
                    if matches!(toks[i].text.as_str(), "match" | "if" | "while" | "in") {
                        start = Some(i + 1);
                    }
                }
                _ => {}
            }
        }
        let Some(start) = start else { return };
        if start >= end {
            return;
        }
        // Only needed when the expression contains a top-level brace.
        let mut d = 0i32;
        let mut has_brace = false;
        for i in start..end {
            match toks[i].kind {
                Tk::Open('{') if d == 0 => has_brace = true,
                Tk::Open(_) => d += 1,
                Tk::Close(_) => d -= 1,
                _ => {}
            }
        }
        if !has_brace {
            return;
        }
        let last = (start..end).rev().find(|&i| !toks[i].is_comment());
        if let Some(last) = last {
            out.insert(start, Fix::Open);
            out.insert(last, Fix::CloseAfter);
        }
    }

    /// Rule 4. In a macro arm's parenthesised matcher, a parenthesised
    /// fragment `($x:expr)` is one parameter and a sequence of them is a comma
    /// list, so `( ($a:expr) ($b:expr) )` is `( $a:expr, $b:expr )` and a
    /// repetition `$( (..) )*` of them is `$( .. ),*` -- the shape a Harsh
    /// call `m! a b` produces. The mapping applies to a matcher, or a
    /// repetition body, with a group at its top level; `( $x:expr )` and
    /// `( $( $arg:tt )* )` are the same in both languages and are untouched.
    /// A bracketed or braced matcher is Rust's (rule 5).
    fn matcher_fixups(toks: &[Token]) -> (Vec<usize>, Vec<usize>) {
        let mut drops = Vec::new();
        let mut commas = Vec::new();
        let sig: Vec<usize> = (0..toks.len()).filter(|&i| !toks[i].is_comment()).collect();
        let mut d = 0i32;
        let mut arrow = None;
        for &i in &sig {
            match toks[i].kind {
                Tk::Open(_) => d += 1,
                Tk::Close(_) => d -= 1,
                Tk::FatArrow if d == 0 => {
                    arrow = Some(i);
                    break;
                }
                _ => {}
            }
        }
        let Some(arrow) = arrow else { return (drops, commas) };
        let Some(&o) = sig.first() else { return (drops, commas) };
        if toks[o].kind != Tk::Open('(') {
            return (drops, commas);
        }
        let Some(c) = matching(toks, o) else { return (drops, commas) };
        if sig.iter().any(|&i| i > c && i < arrow) {
            return (drops, commas);
        }
        Self::map_matcher_group(toks, o, c, &mut drops, &mut commas);
        (drops, commas)
    }

    /// One level of rule 4: returns whether the group held a parenthesised
    /// fragment (and so became a comma list).
    fn map_matcher_group(toks: &[Token], o: usize, c: usize, drops: &mut Vec<usize>, commas: &mut Vec<usize>) -> bool {
        enum Item {
            Group(usize, usize),
            Rep(usize, usize, usize, Option<usize>),
            Run(usize),
        }
        let mut items: Vec<Item> = Vec::new();
        let mut i = o + 1;
        let mut in_run = false;
        while i < c {
            let t = &toks[i];
            if t.is_comment() {
                i += 1;
                continue;
            }
            if t.kind == Tk::Punct && t.text == "$" && i + 1 < c && toks[i + 1].kind == Tk::Open('(') && toks[i + 1].span.lo == t.span.hi {
                let Some(b) = matching(toks, i + 1) else { return false };
                let op = (b + 1 < c && toks[b + 1].kind == Tk::Punct && matches!(toks[b + 1].text.as_str(), "*" | "+" | "?")).then_some(b + 1);
                items.push(Item::Rep(i, i + 1, b, op));
                i = op.map_or(b + 1, |x| x + 1);
                in_run = false;
                continue;
            }
            if t.kind == Tk::Open('(') {
                let Some(b) = matching(toks, i) else { return false };
                items.push(Item::Group(i, b));
                i = b + 1;
                in_run = false;
                continue;
            }
            if !in_run {
                items.push(Item::Run(i));
                in_run = true;
            }
            if let Tk::Open(_) = t.kind {
                i = matching(toks, i).map_or(c, |b| b + 1);
                continue;
            }
            i += 1;
        }
        // Does anything here need mapping? A group at this level, or a
        // repetition whose body does.
        let mut mapped = false;
        for it in &items {
            match it {
                Item::Group(a, b) => {
                    drops.push(*a);
                    drops.push(*b);
                    mapped = true;
                }
                Item::Rep(_, a, b, op) => {
                    if Self::map_matcher_group(toks, *a, *b, drops, commas) {
                        if let Some(op) = op.filter(|&k| toks[k].text != "?") {
                            commas.push(op);
                        }
                    }
                }
                Item::Run(_) => {}
            }
        }
        if !mapped {
            return false;
        }
        for it in items.iter().skip(1) {
            let first = match it {
                Item::Group(a, _) => *a,
                Item::Rep(a, _, _, _) => *a,
                Item::Run(a) => *a,
            };
            commas.push(first);
        }
        true
    }

    fn line_tokens(&mut self, toks: &[Token], drop_last_colon: bool) {
        self.line_tokens_ctx(toks, drop_last_colon, self.stmt_ctx, drop_last_colon)
    }

    fn line_tokens_ctx(
        &mut self,
        toks: &[Token],
        drop_last_colon: bool,
        stmt_block: bool,
        is_header: bool,
    ) {
        // The trailing `:` becomes `{`, and a `do` immediately before it is a
        // hrs-only marker for a bare block -- Rust reserves `do` but has no
        // syntax for it, so it must not reach the output.
        let mut end = toks.len();
        let mut skip_do = usize::MAX;
        if drop_last_colon {
            // (The mark dropped is the header's `:` -- or its `\`, or, on a
            // declaration header that has none, nothing.)
            if let Some(c) = toks.iter().rposition(|t| !t.is_comment()) {
                end = if matches!(toks[c].kind, Tk::Colon | Tk::Backslash | Tk::FatArrow) { c } else { c + 1 };
                if let Some(d) = toks[..c].iter().rposition(|t| !t.is_comment()) {
                    if toks[d].is_kw("do") {
                        skip_do = d;
                    }
                    // `#:` is one mark, not a `#` followed by a block opener:
                    // the `:` goes as any opener does, and the `#` with it.
                    if toks[c].kind == Tk::Colon
                        && toks[d].text == "#"
                        && toks[d].span.hi == toks[c].span.lo
                    {
                        skip_do = d;
                    }
                }
            }
        }
        let braces = Self::brace_groups(toks);
        let jx = match self.forced_jx.take() {
            Some(j) => j,
            None => juxt::fixups(toks, stmt_block, is_header),
        };
        let mut open_at: std::collections::HashMap<usize, usize> = std::collections::HashMap::new();
        let mut comma_at: std::collections::HashSet<usize> = std::collections::HashSet::new();
        let mut close_at: std::collections::HashMap<usize, usize> = std::collections::HashMap::new();
        let mut fixes_drop: std::collections::HashSet<usize> = std::collections::HashSet::new();
        let mut defer_at: std::collections::HashMap<usize, usize> = std::collections::HashMap::new();
        for (i, k) in &jx {
            match k {
                Jx::Open => *open_at.entry(*i).or_insert(0) += 1,
                Jx::Comma => {
                    comma_at.insert(*i);
                }
                Jx::Close => *close_at.entry(*i).or_insert(0) += 1,
                Jx::Drop => {
                    fixes_drop.insert(*i);
                }
                Jx::CloseAfterBlock => *defer_at.entry(*i).or_insert(0) += 1,
            }
        }
        // Rule 4: the parenthesised matcher of a `macro_rules!` arm is a
        // Harsh parameter list -- one group per fragment.
        if self.kind == BlockKind::MacroRules {
            let (drops, commas) = Self::matcher_fixups(toks);
            fixes_drop.extend(drops);
            comma_at.extend(commas);
        }
        let mut fixes = Self::param_fixups(toks);
        if let Some(k) = self.forced_skip.take() {
            fixes.insert(k, Fix::Skip);
            // The juxtaposition's own Drop of the same paren is moot.
            fixes_drop.remove(&k);
        }
        Self::where_fixups(toks, &mut fixes);
        if drop_last_colon {
            Self::scrutinee_fixups(toks, &mut fixes);
        }
        Self::backslash_fixups(toks, end, &mut fixes, &mut comma_at);
        let mut prev: Option<Token> = None;
        for (i, t) in toks.iter().enumerate() {
            if drop_last_colon && (i == end || i == skip_do) {
                continue;
            }
            match fixes.get(&i) {
                Some(Fix::Skip) => {
                    // The whitespace *before* a skipped token still belongs to
                    // the token that precedes it, so emit it; then advance
                    // `prev` past the skipped token, or the gap copy would
                    // re-emit the very token we dropped.
                    if let Some(p) = prev.as_ref() {
                        if t.span.lo > p.span.hi {
                            let gap = &self.src[p.span.hi as usize..t.span.lo as usize];
                            // A line break before a dropped bracket collapses to
                            // a single space: `-> T\n  [where ..]` is one
                            // signature, not two lines.
                            // Never stack whitespace: a dropped empty group has
                            // a gap on both sides of it.
                            // A dropped `(` after a callee takes no gap: the
                            // next group sits against the name.
                            let call = t.kind == Tk::Open('(')
                                && matches!(p.kind, Tk::Ident | Tk::Gt)
                                && !crate::rules::is_keyword(&p.text);
                            if !call && !self.out.ends_with(' ') && !self.out.ends_with('\n') {
                                // ... except after a line comment, which
                                // must end its line: the break stays.
                                if gap.contains('\n') && p.kind == Tk::LineComment {
                                    let tail = gap.rsplit('\n').next().unwrap_or("");
                                    self.out.push('\n');
                                    for _ in 0..self.level {
                                        self.out.push_str("    ");
                                    }
                                    self.out.push_str(tail);
                                } else if gap.contains('\n') {
                                    self.out.push(' ');
                                } else {
                                    self.out.push_str(gap);
                                }
                            }
                        }
                    }
                    prev = Some(t.clone());
                    continue;
                }
                Some(Fix::Text(s)) => {
                    let lo = self.here();
                    self.out.push_str(s);
                    let hi = self.here();
                    self.map.push(MapEntry {
                        gen_lo: lo,
                        gen_hi: hi,
                        src_lo: t.span.lo,
                        src_hi: t.span.hi,
                    });
                    prev = Some(t.clone());
                    continue;
                }
                Some(fix @ (Fix::Open | Fix::Wrap)) => {
                    // The invented `(` of a bare parameter list sits against
                    // the function name, `fn g(name: &str)`; the one wrapping a
                    // `match`/`if` scrutinee keeps the keyword's space.
                    if let Some(p) = prev.as_ref() {
                        let callee = matches!(p.kind, Tk::Ident | Tk::Gt) && !crate::rules::is_keyword(&p.text);
                        if t.span.lo > p.span.hi && !callee {
                            self.out.push(' ');
                        }
                    }
                    self.out.push('(');
                    let tf = Self::needs_turbofish(toks, i);
                    let mut t2 = t.clone();
                    t2.span.lo = t.span.lo;
                    self.tok(&t2, None, tf, braces.contains(&i));
                    if matches!(fix, Fix::Wrap) {
                        self.out.push(')');
                    }
                    prev = Some(t.clone());
                    continue;
                }
                Some(Fix::CloseAfter) => {
                    let tf = Self::needs_turbofish(toks, i);
                    self.tok(t, prev.as_ref(), tf, braces.contains(&i));
                    self.out.push(')');
                    prev = Some(t.clone());
                    continue;
                }
                Some(Fix::TextAfter(s)) => {
                    let tf = Self::needs_turbofish(toks, i);
                    self.tok(t, prev.as_ref(), tf, braces.contains(&i));
                    self.out.push_str(s);
                    prev = Some(t.clone());
                    continue;
                }
                None => {}
            }
            let tf = Self::needs_turbofish(toks, i);
            if fixes_drop.contains(&i) {
                if comma_at.contains(&i) {
                    while self.out.ends_with(' ') {
                        self.out.pop();
                    }
                    self.out.push(',');
                    self.out.push(' ');
                } else if let Some(p) = prev.as_ref() {
                    // A dropped opener keeps the space that preceded it, so
                    // `= (1 + 2)` becomes `= 1 + 2`, not `=1 + 2`.
                    let gap = &self.src[p.span.hi as usize..t.span.lo as usize];
                    if t.kind == Tk::Open('(') && !gap.is_empty() && !self.out.ends_with(' ') && !self.out.ends_with('(') {
                        self.out.push(' ');
                    }
                }
                if let Some(n) = open_at.get(&i) {
                    while self.out.ends_with(' ') {
                        self.out.pop();
                    }
                    for _ in 0..*n {
                        self.out.push('(');
                    }
                }
                if let Some(n) = close_at.get(&i) {
                    for _ in 0..*n {
                        self.out.push(')');
                    }
                }
                prev = Some(t.clone());
                continue;
            }
            if let Some(n) = comma_at.get(&i).map(|_| 1) {
                let _ = n;
                while self.out.ends_with(' ') {
                    self.out.pop();
                }
                self.out.push(',');
            }
            if let Some(n) = open_at.get(&i) {
                while self.out.ends_with(' ') {
                    self.out.pop();
                }
                for _ in 0..*n {
                    self.out.push('(');
                }
                self.tok(t, None, tf, braces.contains(&i));
            } else {
                self.tok(t, prev.as_ref(), tf, braces.contains(&i));
            }
            if let Some(n) = close_at.get(&i) {
                for _ in 0..*n {
                    self.out.push(')');
                }
            }
            if let Some(n) = defer_at.get(&i) {
                self.pending_close += *n;
            }
            prev = Some(t.clone());
        }
    }

    fn blanks(&mut self, n: usize) {
        for _ in 0..n.min(2) {
            self.out.push('\n');
        }
    }

    fn comments(&mut self, l: &Line) {
        for c in &l.comments {
            self.indent();
            let lo = self.here();
            self.out.push_str(&c.text);
            let hi = self.here();
            self.map.push(MapEntry { gen_lo: lo, gen_hi: hi, src_lo: c.span.lo, src_hi: c.span.hi });
            self.out.push('\n');
        }
    }

    pub fn program(&mut self, nodes: &[Node]) {
        self.nodes(nodes, BlockKind::Items);
    }

    /// Is this header a macro call? `m!\` and `m~\` open a literal-shaped
    /// block whose entries are the macro's, so the last one takes no comma:
    /// a matcher of fixed arity refuses a trailing separator, while Rust's
    /// own struct literals and fields accept one and keep it (rustfmt writes
    /// it, and the corpus is written that way).
    fn macro_header(toks: &[Token]) -> bool {
        toks.iter()
            .any(|t| (t.text == "!" || t.text == "~") && t.kind != Tk::Str)
    }

    fn nodes(&mut self, nodes: &[Node], kind: BlockKind) {
        let saved_ctx = self.stmt_ctx;
        let saved_kind = self.kind;
        self.stmt_ctx = matches!(kind, BlockKind::Stmts | BlockKind::Arms | BlockKind::Macro | BlockKind::Rep);
        self.kind = kind;
        let last = last_value_index(nodes);
        // An `else` block terminates the statement its `if` began, so it
        // inherits the leading keyword of the chain rather than using `else`.
        let mut chain_kw: Option<String> = None;
        let mut chain_assigns = false;
        for (i, n) in nodes.iter().enumerate() {
            // In a repetition every statement takes `;`, the last included.
            let is_last = Some(i) == last && kind != BlockKind::Rep;
            // `let x = if c: .. else: ..` must not put a `;` after the `if`
            // block, or the `else` is orphaned.
            let next_is_else = nodes
                .get(i + 1)
                .map(|n| {
                    let t = match n {
                        Node::Line(l) => &l.toks,
                        Node::Block(b) => &b.header.toks,
                        Node::Markup(_) | Node::Group(_) | Node::Tree(_) => return false,
                    };
                    first_kw(t) == Some("else")
                })
                .unwrap_or(false);
            match n {
                Node::Line(l) if kind == BlockKind::Lit => {
                    self.blanks(l.blank_before);
                    self.comments(l);
                    self.indent();
                    let body_end = l.toks.iter().rposition(|t| !t.is_comment()).map(|i| i + 1).unwrap_or(0);
                    let (body, trail) = l.toks.split_at(body_end);
                    // A comment-only line is just its comment.
                    if !body.is_empty() {
                        self.lit_line_at(body, is_last && self.macro_lit);
                    }
                    for c in trail {
                        self.out.push(' ');
                        let lo = self.here();
                        self.out.push_str(&c.text);
                        let hi = self.here();
                        self.map.push(MapEntry { gen_lo: lo, gen_hi: hi, src_lo: c.span.lo, src_hi: c.span.hi });
                    }
                    self.out.push('\n');
                }
                Node::Markup(toks) => self.markup(toks),
                Node::Group(g) => {
                    self.indent();
                    self.group(g);
                    self.out.push('\n');
                }
                Node::Tree(parts) => {
                    self.indent();
                    self.tree_line(parts);
                    self.out.push('\n');
                }
                Node::Line(l) => {
                    self.blanks(l.blank_before);
                    self.comments(l);
                    self.indent();
                    // A comment at the end of the line stays at the end: the
                    // separator goes before it, or it would be commented out.
                    let body_end = l.toks.iter().rposition(|t| !t.is_comment()).map(|i| i + 1).unwrap_or(0);
                    let (body, trail) = l.toks.split_at(body_end);
                    self.line_tokens(body, false);
                    if !body.is_empty() {
                        // In a macro body a line with a top-level `=>` is an
                        // arm and takes `,`; every other line is a statement.
                        let eff_kind = match kind {
                            BlockKind::Macro if has_top_level_arrow(body) => BlockKind::Arms,
                            BlockKind::Macro => BlockKind::Stmts,
                            k => k,
                        };
                        self.separator(
                            eff_kind,
                            first_kw(body),
                            is_last,
                            ends_with_semi(body),
                            false,
                            false,
                            false,
                        );
                    }
                    for c in trail {
                        if !body.is_empty() {
                            self.out.push(' ');
                        }
                        let lo = self.here();
                        self.out.push_str(&c.text);
                        let hi = self.here();
                        self.map.push(MapEntry { gen_lo: lo, gen_hi: hi, src_lo: c.span.lo, src_hi: c.span.hi });
                    }
                    self.out.push('\n');
                }
                Node::Block(b) => {
                    self.blanks(b.header.blank_before);
                    self.comments(&b.header);
                    self.indent();
                    self.block(b);
                    let own = first_kw(&b.header.toks);
                    let is_else = own == Some("else");
                    let eff = if is_else {
                        chain_kw.clone()
                    } else {
                        own.map(|s| s.to_string())
                    };
                    let eff_assigns = if is_else {
                        chain_assigns
                    } else {
                        has_top_level_eq(&b.header.toks)
                    };
                    chain_kw = if next_is_else { eff.clone() } else { None };
                    chain_assigns = next_is_else && eff_assigns;
                    if !next_is_else {
                        let eff_kind = match kind {
                            BlockKind::Macro if b.arrow_opener || has_top_level_arrow(&b.header.toks) => BlockKind::Arms,
                            BlockKind::Macro => BlockKind::Stmts,
                            k => k,
                        };
                        // A literal block that is the value of a `let`, or a
                        // statement, ends its statement with `;`.
                        let eff_kind = if b.kind == BlockKind::Lit && kind == BlockKind::Stmts { BlockKind::Stmts } else { eff_kind };
                        // A tail that ends in a written `;` already ends the
                        // statement. A block whose tail is a line -- a paren
                        // block, `f (Point:` .. `)` -- is an expression
                        // statement and takes `;` like a line, unless last.
                        // Through nested tails (`(P\ ..) + (P\ ..)` on one
                        // line): the statement ends where the innermost
                        // tail does.
                        let mut last_tail: &Block = b;
                        while let Some(Node::Block(inner)) = last_tail.tail.last() {
                            last_tail = inner;
                        }
                        let tail_semi = matches!(last_tail.tail.last(), Some(Node::Line(l)) if ends_with_semi(&l.toks));
                        let tail_is_line = matches!(last_tail.tail.last(), Some(Node::Line(_)));
                        let eff_kind = if tail_is_line && !ends_in_closure_ret(&b.header.toks) { eff_kind } else { eff_kind };
                        self.separator(
                            eff_kind,
                            eff.as_deref(),
                            is_last,
                            tail_semi,
                            !tail_is_line,
                            eff_assigns,
                            // A tail that opens the statement's own block
                            // (`):` and the `if` body) makes it a block
                            // statement, not a closure call.
                            header_ends_in_closure(&b.header.toks) && !matches!(b.tail.last(), Some(Node::Block(_))),
                        );
                    }
                    self.out.push('\n');
                }
            }
        }
        self.stmt_ctx = saved_ctx;
        self.kind = saved_kind;
    }

    /// A `\` that reached the emitter in a line: a pattern (`let Point\ x,
    /// y = p`, `Point\ x, .. =>`) or a literal inside a header (`match
    /// (Point\ x = 1):`). Written `Point { .. }`: the `\` becomes ` {`, the
    /// item run ends with ` }` at its bound -- `=`, `=>`, `in`, `if`, `|`,
    /// the `)` closing its group, or the line's end -- and in a literal each
    /// field's `=` becomes `:`.
    fn backslash_fixups(toks: &[Token], end: usize, fixes: &mut std::collections::HashMap<usize, Fix>, _comma_at: &mut std::collections::HashSet<usize>) {
        let mut i = 0;
        while i < end {
            if toks[i].kind != Tk::Backslash {
                i += 1;
                continue;
            }
            let is_pattern = crate::layout::pattern_backslash(toks, 0, end, i);
            fixes.insert(i, Fix::Text(" {"));
            // The bound.
            let mut d = 0i32;
            let mut last: Option<usize> = None;
            let mut k = i + 1;
            while k < end {
                let t = &toks[k];
                if t.is_comment() {
                    k += 1;
                    continue;
                }
                match t.kind {
                    Tk::Open(_) => d += 1,
                    Tk::Close(_) => {
                        if d == 0 {
                            break;
                        }
                        d -= 1;
                    }
                    Tk::FatArrow if d == 0 => break,
                    Tk::Eq if d == 0 && is_pattern => break,
                    Tk::Eq if d == 0 && !is_pattern => {
                        // A field's `=` is Rust's `:`.
                        fixes.insert(k, Fix::Text(":"));
                    }
                    Tk::Ident if d == 0 && is_pattern && (t.is_kw("in") || t.is_kw("if")) => break,
                    Tk::Punct if d == 0 && is_pattern && t.text == "|" => break,
                    _ => {}
                }
                last = Some(k);
                k += 1;
            }
            match last {
                Some(l) => {
                    let cur = fixes.get(&l).cloned();
                    fixes.insert(
                        l,
                        match cur {
                            Some(Fix::Text(":")) => Fix::TextAfter(" }"),
                            _ => Fix::TextAfter(" }"),
                        },
                    );
                }
                None => {
                    fixes.insert(i, Fix::Text(" {}"));
                }
            }
            i = k.max(i + 1);
        }
    }

    /// One line of a struct literal: `field = expr` is written `field: expr,`
    /// (the expression juxtaposes as anywhere); a bare `field` is the
    /// shorthand; `..base` is written as it is, and takes no comma.
    fn lit_line(&mut self, toks: &[Token]) {
        self.lit_line_at(toks, false)
    }

    /// `is_last` suppresses the separator: no trailing comma (2026-09-17).
    /// A grammar that takes `a, b` takes it without a final comma, and a
    /// macro matcher of fixed arity -- `( $a:expr, $b:expr )` -- refuses one.
    fn lit_line_at(&mut self, toks: &[Token], is_last: bool) {
        let sig: Vec<usize> = (0..toks.len()).filter(|&i| !toks[i].is_comment()).collect();
        let is_spread = sig.first().map_or(false, |&i| toks[i].kind == Tk::DotDot);
        let is_field = sig.len() >= 3 && toks[sig[0]].kind == Tk::Ident && toks[sig[1]].kind == Tk::Eq;
        if is_field {
            let name = &toks[sig[0]];
            let lo = self.here();
            self.out.push_str(&name.text);
            self.out.push(':');
            let hi = self.here();
            self.map.push(MapEntry { gen_lo: lo, gen_hi: hi, src_lo: name.span.lo, src_hi: name.span.hi });
            self.out.push(' ');
            self.line_tokens_ctx(&toks[sig[2]..], false, true, false);
        } else {
            self.line_tokens_ctx(toks, false, !is_spread, false);
        }
        if !is_spread && !is_last {
            self.out.push(',');
        }
    }

    /// A run of markup inside an HSX block: the tokens as written, with the
    /// token substitutions and nothing else. `.` in a component path is a
    /// path separator here as everywhere.
    fn markup(&mut self, toks: &[Token]) {
        self.line_tokens_ctx(toks, false, false, false);
    }

    /// A delimited Harsh fragment in a macro body -- a `{ .. }` hole or a
    /// `$( .. )*` repetition. Its body indents one level past the line that
    /// holds the opener, and the closer returns to that line's column, as the
    /// source wrote them.
    fn group(&mut self, g: &Group) {
        let mut prev: Option<&Token> = None;
        if !g.bare {
            for t in &g.open {
                self.tok(t, prev, false, false);
                prev = Some(t);
            }
        }
        let saved = self.level;
        self.level += 1;
        if g.body_own_line {
            self.out.push('\n');
            self.nodes(&g.body, g.kind);
            self.level = saved;
            if !self.out.ends_with('\n') {
                self.out.push('\n');
            }
            self.indent();
        } else {
            self.skip_indent = true;
            self.nodes(&g.body, g.kind);
            self.skip_indent = false;
            self.level = saved;
            if self.out.ends_with('\n') {
                self.out.pop();
            }
            // A closer on its own line in the source: when the body ended in
            // a generated `}` the closer shares its line, `}}>`, so the line
            // count is kept; otherwise it takes a line of its own.
            if g.close.first().map_or(false, |t| t.line_start.is_some()) && !self.out.ends_with('}') {
                self.out.push('\n');
                self.indent();
            }
        }
        if g.bare {
            return;
        }
        let mut prev: Option<&Token> = None;
        for t in &g.close {
            self.tok(t, prev, false, false);
            prev = Some(t);
        }
    }

    /// One line of a brace tree (rule 6). Its shape is read from the first
    /// run: `name = value` is an attribute, `name: value,`, and a hole's
    /// braces are dropped there because `rsx!` recognises an event handler by
    /// its leading `move` or `|`; `name: rest` is an inline element,
    /// `name { rest }`; anything else -- a string, a `{ .. }` hole, a
    /// `..spread` -- is a child, copied, a spread being an attribute for the
    /// comma's purposes. Verified against `dioxus-rsx` 0.7: only attributes
    /// take commas.
    fn tree_line(&mut self, parts: &[Node]) {
        let first: Vec<&Token> = match parts.first() {
            Some(Node::Markup(t)) => t.iter().filter(|t| !t.is_comment()).collect(),
            _ => Vec::new(),
        };
        // `name` or `a.b.name` at the start, and what follows it.
        let mut i = 0;
        if first.get(0).map_or(false, |t| t.kind == Tk::Ident) {
            i = 1;
            while i + 1 < first.len() && first[i].kind == Tk::Dot && first[i + 1].kind == Tk::Ident {
                i += 2;
            }
        }
        let after = first.get(i).map(|t| t.kind.clone());
        let is_attr = i > 0 && after == Some(Tk::Eq);
        let is_inline_element = i > 0 && after == Some(Tk::Colon);
        let is_spread = first.first().map_or(false, |t| t.kind == Tk::DotDot);
        let mut prev_hi: Option<u32> = None;
        // The attribute's `=`, to be written `:`; and whether its value is a
        // lone hole whose braces go.
        let eq_span = if is_attr { Some(first[i].span) } else { None };
        let colon_span = if is_inline_element { Some(first[i].span) } else { None };
        let lone_hole = is_attr
            && parts.len() == 2
            && matches!(parts.get(1), Some(Node::Group(_)))
            && first.last().map_or(false, |t| t.kind == Tk::Eq);
        for (n, part) in parts.iter().enumerate() {
            match part {
                Node::Markup(toks) => {
                    for t in toks {
                        if let Some(ph) = prev_hi {
                            self.gap(ph, t.span.lo);
                        }
                        let lo = self.here();
                        if Some(t.span) == eq_span {
                            while self.out.ends_with(' ') {
                                self.out.pop();
                            }
                            self.out.push(':');
                        } else if n == 0 && Some(t.span) == colon_span {
                            if !self.out.ends_with(' ') {
                                self.out.push(' ');
                            }
                            self.out.push('{');
                        } else {
                            match t.kind {
                                Tk::Dot => self.out.push_str("::"),
                                Tk::LArrow => self.out.push('.'),
                                _ => self.out.push_str(&t.text),
                            }
                        }
                        let hi = self.here();
                        self.map.push(MapEntry { gen_lo: lo, gen_hi: hi, src_lo: t.span.lo, src_hi: t.span.hi });
                        prev_hi = Some(t.span.hi);
                    }
                }
                Node::Group(g) => {
                    if let Some(ph) = prev_hi {
                        self.gap(ph, g.open[0].span.lo);
                    }
                    if lone_hole {
                        self.group_inner(g);
                    } else {
                        self.group(g);
                    }
                    prev_hi = Some(g.close.last().unwrap().span.hi);
                }
                _ => {}
            }
        }
        if is_inline_element {
            self.out.push_str(" }");
        }
        if is_attr || is_spread {
            self.out.push(',');
        }
    }

    /// A hole's body without its braces: the value of a tree attribute.
    fn group_inner(&mut self, g: &Group) {
        let saved = self.level;
        self.level += 1;
        self.skip_indent = true;
        self.nodes(&g.body, g.kind);
        self.skip_indent = false;
        self.level = saved;
        if self.out.ends_with('\n') {
            self.out.pop();
        }
    }

    fn block(&mut self, b: &Block) {
        let before = self.out.len();
        // A comment at the end of the header stays at the end: the brace goes
        // before it, or it would be commented out -- the same rule as for a
        // line's separator.
        let body_end = b.header.toks.iter().rposition(|t| !t.is_comment()).map(|i| i + 1).unwrap_or(0);
        let (head, trail) = b.header.toks.split_at(body_end);
        // Optional grouping around a whole block -- `(C\ n: u8)` as one
        // item of an inline enum, `(fn #name$ do: ..)` in a `quote!` -- is
        // not emitted: the `(` opens the header and the tail is only its `)`.
        // The last `(` left open in the head, if any, and what precedes it.
        let last_open: Option<usize> = {
            let mut stack: Vec<usize> = Vec::new();
            for (k, t) in head.iter().enumerate() {
                match t.kind {
                    Tk::Open('(') if !t.synthetic => stack.push(k),
                    Tk::Open(_) => stack.push(usize::MAX),
                    Tk::Close(_) => {
                        stack.pop();
                    }
                    _ => {}
                }
            }
            stack.last().copied().filter(|&k| k != usize::MAX)
        };
        let tail_starts_close = matches!(b.tail.first(), Some(Node::Line(l)) if l.toks.iter().find(|t| !t.is_comment()).map_or(false, |t| t.kind == Tk::Close(')')));
        // The parens are optional grouping when they hold the whole block
        // and are not a call's: what precedes the `(` is `=`, `,`, `[`,
        // `(`, `=>`, an operator, or the line's start -- not a name (an
        // application, `Some (if c:`) and not a macro's bang. A `(do:` is
        // always optional: the block's braces isolate it already.
        let whole_group = last_open.map_or(false, |p| {
            let after: Vec<&Token> = head[p + 1..].iter().filter(|t| !t.is_comment()).collect();
            let is_do = after.first().map_or(false, |t| t.is_kw("do"));
            let before = (0..p).rev().find(|&k| !head[k].is_comment()).map(|k| &head[k]);
            let not_call = match before {
                None => true,
                Some(t) => {
                    matches!(t.kind, Tk::Eq | Tk::Comma | Tk::Open('[') | Tk::Open('(') | Tk::FatArrow)
                        || t.is_kw("return")
                        || (t.kind == Tk::Punct && !matches!(t.text.as_str(), "!" | "$" | "?"))
                }
            };
            // A tuple's paren -- a top-level comma between the `(` and the
            // block -- is a construct, kept.
            let tuple = {
                let mut d = 0i32;
                let mut comma = false;
                for t in &head[p + 1..] {
                    match t.kind {
                        Tk::Open(_) => d += 1,
                        Tk::Close(_) => d -= 1,
                        Tk::Comma if d == 0 => comma = true,
                        Tk::Backslash if d == 0 => break,
                        _ => {}
                    }
                }
                comma
            };
            // (A `(do:` that is an argument -- `routes (do:` -- keeps its
            // parens: they are the call's.)
            tail_starts_close && not_call && !tuple && (is_do || true)
        });
        // The dropped `(` is skipped when the head is written (its index
        // must stay, since the fixups are computed on the head as it is).
        self.forced_skip = if whole_group { last_open } else { None };
        // A `macro_rules!` arm's header is a matcher, not an expression: it
        // is written without juxtaposition (its rule-4 mapping is applied in
        // `line_tokens_ctx`), with the `do:` still dropped.
        if self.kind == BlockKind::MacroRules || self.kind == BlockKind::Tree {
            self.line_tokens_ctx(head, !b.arrow_opener, false, false);
        } else if self.kind == BlockKind::Lit && head.len() >= 3 && head[0].kind == Tk::Ident && head[1].kind == Tk::Eq {
            // A nested literal inside a literal: `origin = Point:` opens
            // `origin: Point {`.
            let lo = self.here();
            self.out.push_str(&head[0].text);
            self.out.push(':');
            let hi = self.here();
            self.map.push(MapEntry { gen_lo: lo, gen_hi: hi, src_lo: head[0].span.lo, src_hi: head[0].span.hi });
            self.out.push(' ');
            self.line_tokens_ctx(&head[2..], !b.arrow_opener, true, false);
        } else {
            self.line_tokens(head, !b.arrow_opener);
        }
        // A bare `do:` leaves an empty header, so the brace needs no space.
        if self.out.len() == before {
            self.out.push('{');
        } else {
            self.out.push_str(" {");
        }
        for c in trail {
            self.out.push(' ');
            let lo = self.here();
            self.out.push_str(&c.text);
            let hi = self.here();
            self.map.push(MapEntry { gen_lo: lo, gen_hi: hi, src_lo: c.span.lo, src_hi: c.span.hi });
        }
        // HSX: markup runs and holes, each preceded by the source gap that
        // separates it from what came before -- the first run's gap is the
        // line break after `do:` and the markup's own indentation.
        if b.kind == BlockKind::Hsx {
            let mut prev_hi = head.last().map(|t| t.span.hi).unwrap_or(0);
            let saved_kind = self.kind;
            self.kind = BlockKind::Hsx;
            self.level += 1;
            for part in &b.body {
                match part {
                    Node::Markup(toks) => {
                        self.gap(prev_hi, toks[0].span.lo);
                        self.markup(toks);
                        prev_hi = toks.last().unwrap().span.hi;
                    }
                    Node::Group(g) => {
                        self.gap(prev_hi, g.open[0].span.lo);
                        self.group(g);
                        prev_hi = g.close.last().unwrap().span.hi;
                    }
                    Node::Line(_) | Node::Block(_) | Node::Tree(_) => {}
                }
            }
            self.level -= 1;
            self.kind = saved_kind;
            self.out.push('\n');
            self.indent();
            self.out.push('}');
            // A markup block opened inside a group has a tail too: the
            // `)` and whatever continues the statement.
            for n in &b.tail {
                match n {
                    Node::Line(l) => self.line_tokens_ctx(&l.toks, false, self.stmt_ctx, false),
                    Node::Block(b2) => self.block(b2),
                    _ => {}
                }
            }
            return;
        }
        self.out.push('\n');
        let owed = std::mem::take(&mut self.pending_close);
        self.level += 1;
        let saved_macro_lit = self.macro_lit;
        self.macro_lit = Self::macro_header(&b.header.toks);
        self.nodes(&b.body, b.kind);
        self.macro_lit = saved_macro_lit;
        self.level -= 1;
        self.indent();
        self.out.push('}');
        for _ in 0..owed {
            self.out.push(')');
        }
        // The rest of the statement, when the block was opened inside a
        // paren: begins with the `)` that closed it, then any chain. (A
        // whole-group tail -- only the `)` -- was dropped with its `(`.)
        let mut first = true;
        for n in &b.tail {
            match n {
                Node::Line(l) if first && whole_group => {
                    // The tail without the `)` that matched the dropped `(`.
                    let close = l.toks.iter().position(|t| !t.is_comment()).unwrap_or(0);
                    let mut rest: Vec<Token> = l.toks.clone();
                    rest.remove(close);
                    if rest.iter().any(|t| !t.is_comment()) {
                        self.line_tokens_ctx(&rest, false, self.stmt_ctx, false);
                    }
                }
                Node::Line(l) if first && !whole_group && (last_open.is_some() || head.iter().find(|t| !t.is_comment()).map_or(false, |t| t.is_kw("else"))) => {
                    // The block was an argument, `push (if c: a else: b) lo`:
                    // the `)` closed its group, and atoms after it are the
                    // call's further arguments -- `, lo)`.
                    let sig: Vec<usize> = (0..l.toks.len()).filter(|&i| !l.toks[i].is_comment()).collect();
                    let more_args = sig.len() >= 2
                        && l.toks[sig[0]].kind == Tk::Close(')')
                        && matches!(l.toks[sig[1]].kind, Tk::Ident | Tk::Str | Tk::Int | Tk::Float | Tk::Char | Tk::Open('(') | Tk::Open('['))
                        && !crate::rules::is_keyword(&l.toks[sig[1]].text)
                        && !l.toks[sig[1]].is_kw("as");
                    if more_args {
                        let mut rest: Vec<Token> = l.toks.clone();
                        rest.remove(sig[0]);
                        // A written `;` comes after the `)`.
                        let semi = rest.iter().rposition(|t| !t.is_comment()).filter(|&k| rest[k].kind == Tk::Semi).map(|k| rest.remove(k));
                        self.out.push_str(", ");
                        // The atoms are one argument list: commas between,
                        // the isolating parens of groups dropped.
                        let jx = juxt::args_only(&rest);
                        self.line_tokens_with(&rest, jx);
                        self.out.push(')');
                        if semi.is_some() {
                            self.out.push(';');
                        }
                    } else {
                        self.line_tokens_ctx(&l.toks, false, self.stmt_ctx, false);
                    }
                }
                Node::Line(l) => self.line_tokens_ctx(&l.toks, false, self.stmt_ctx, false),
                Node::Block(b2) => self.block(b2),
                _ => {}
            }
            first = false;
        }
    }

    /// Write a line with a given set of juxtaposition fixups instead of the
    /// computed ones.
    fn line_tokens_with(&mut self, toks: &[Token], jx: Vec<(usize, juxt::Jx)>) {
        self.forced_jx = Some(jx);
        self.line_tokens_ctx(toks, false, self.stmt_ctx, false);
        self.forced_jx = None;
    }

    fn separator(
        &mut self,
        kind: BlockKind,
        kw: Option<&str>,
        is_last: bool,
        already_semi: bool,
        is_block: bool,
        assigns: bool,
        closure_call: bool,
    ) {
        let ends_brace = self.out.ends_with('}');
        if kw == Some("#") {
            return; // attribute line
        }
        match kind {
            BlockKind::Items => {
                // A non-block line in an item position is a declaration without
                // a body -- a trait method signature, an associated type or
                // const, a `use`, or an item macro. All of them terminate with
                // `;`. Lines that *do* have a body arrive here as blocks.
                let force = kw.map(|k| ALWAYS_SEMI.contains(&k)).unwrap_or(false);
                if !already_semi && !is_block && (force || !ends_brace) {
                    self.out.push(';');
                }
            }
            BlockKind::Fields | BlockKind::Arms => {
                self.out.push(',');
            }
            // A struct literal's fields take `,`; the writer of a `..base`
            // line writes none (Rust allows none after it).
            BlockKind::Lit => {
                // No separator after the last entry (2026-09-17): a grammar
                // that takes `a, b` always takes it without a final comma,
                // and a macro matcher with a fixed arity -- `( $a:expr,
                // $b:expr )` -- refuses one outright.
                if !already_semi && !(is_last && self.macro_lit) {
                    self.out.push(',');
                }
            }
            // Each arm of a `macro_rules!` body ends in `;`.
            BlockKind::MacroRules => {
                if !already_semi {
                    self.out.push(';');
                }
            }
            // `#:` writes nothing between entries: the block's grammar is its
            // author's, and Harsh supplies only the braces and the lines.
            BlockKind::Bare => {}
            // Markup never reaches here; a tree line writes its own comma,
            // and a tree's blocks take none.
            BlockKind::Hsx | BlockKind::Macro | BlockKind::Tree => {}
            BlockKind::Stmts | BlockKind::Rep => {
                if already_semi {
                    return;
                }
                let force = kw.map(|k| ALWAYS_SEMI.contains(&k)).unwrap_or(false);
                if is_block && closure_call {
                    // A statement whose expression contains an indented
                    // closure is a statement, not a block: `v <- sort_by |a, b|:`
                    // followed by another statement ends in `;` like any other.
                    // The closure body is governed at its own level by the same
                    // rule, recursively.
                    if force || !is_last {
                        self.out.push(';');
                    }
                } else if is_block {
                    // `}` needs `;` only when the block produced a value that
                    // the statement consumes. A top-level `=` in the header is
                    // the signal; `if {}` and `match {}` as statements are not.
                    if kw.map(|k| BLOCK_NEEDS_SEMI.contains(&k)).unwrap_or(false) || assigns {
                        self.out.push(';');
                    }
                } else if force || !is_last {
                    self.out.push(';');
                }
            }
        }
    }
}

/// The relative path from `from` to `to` (both directories, relative to
/// the same root), as `../../src`-style text; `None` when they are one.
fn relative_dir(from: &std::path::Path, to: &std::path::Path) -> Option<String> {
    let f: Vec<_> = from.components().map(|c| c.as_os_str().to_string_lossy().to_string()).collect();
    let t: Vec<_> = to.components().map(|c| c.as_os_str().to_string_lossy().to_string()).collect();
    let common = f.iter().zip(t.iter()).take_while(|(a, b)| a == b).count();
    let mut parts: Vec<String> = vec!["..".to_string(); f.len() - common];
    parts.extend(t[common..].iter().cloned());
    if parts.is_empty() {
        None
    } else {
        Some(parts.join("/"))
    }
}

/// Collapse `a/../b` and `./b` in a relative path.
fn normalize_path(p: &str) -> String {
    let mut out: Vec<&str> = Vec::new();
    for part in p.split('/') {
        match part {
            "" | "." => {}
            ".." => {
                if matches!(out.last(), Some(&x) if x != "..") {
                    out.pop();
                } else {
                    out.push("..");
                }
            }
            x => out.push(x),
        }
    }
    out.join("/")
}

/// The index of the bracket closing the one at `i`.
fn matching(toks: &[Token], i: usize) -> Option<usize> {
    let mut d = 0i32;
    for k in i..toks.len() {
        match toks[k].kind {
            Tk::Open(_) => d += 1,
            Tk::Close(_) => {
                d -= 1;
                if d == 0 {
                    return Some(k);
                }
            }
            _ => {}
        }
    }
    None
}

/// Whether a line has a `=>` at bracket depth zero: an arm.
fn has_top_level_arrow(toks: &[Token]) -> bool {
    let mut d = 0i32;
    for t in toks {
        match t.kind {
            Tk::Open(_) => d += 1,
            Tk::Close(_) => d -= 1,
            Tk::FatArrow if d == 0 => return true,
            _ => {}
        }
    }
    false
}

fn ends_in_closure_ret(_toks: &[Token]) -> bool {
    false
}

fn first_kw(toks: &[Token]) -> Option<&str> {
    let mut it = toks.iter().filter(|t| !t.is_comment());
    let first = it.next()?;
    if first.kind == Tk::Hash {
        return Some("#");
    }
    // Skip visibility and other modifiers, so `pub const X = ..` is still
    // recognised as a `const` and terminates with `;`.
    let mut t = first;
    while t.kind == Tk::Ident && crate::rules::MODIFIERS.contains(&t.text.as_str()) {
        match it.next() {
            Some(n) => t = n,
            None => break,
        }
    }
    if t.kind == Tk::Ident {
        Some(t.text.as_str())
    } else {
        None
    }
}

fn ends_with_semi(toks: &[Token]) -> bool {
    toks.iter().rev().find(|t| !t.is_comment()).map(|t| t.kind == Tk::Semi).unwrap_or(false)
}

/// The index of the node that would be the block's tail value. Attribute lines
/// and comment-only lines cannot be it.
fn last_value_index(nodes: &[Node]) -> Option<usize> {
    nodes
        .iter()
        .enumerate()
        .rev()
        .find(|(_, n)| {
            let toks = match n {
                Node::Line(l) => &l.toks,
                Node::Block(b) => &b.header.toks,
                Node::Markup(_) | Node::Group(_) | Node::Tree(_) => return true,
            };
            first_kw(toks) != Some("#") && toks.iter().any(|t| !t.is_comment())
        })
        .map(|(i, _)| i)
}


/// Whether the header assigns the block's value to something.
///
/// An `=` only counts when it appears *before* the block keyword. `if let
/// Some(p) = x:` and `while let Some(t) = s.pop():` both contain a top-level
/// `=`, but it binds a pattern in the condition -- the block is not a value.
fn has_top_level_eq(toks: &[Token]) -> bool {
    let mut d = 0i32;
    for t in toks {
        match t.kind {
            Tk::Open(_) => d += 1,
            Tk::Close(_) => d -= 1,
            Tk::Ident
                if d == 0
                    && matches!(
                        t.text.as_str(),
                        "if" | "while" | "for" | "loop" | "match" | "unsafe" | "fn" | "do"
                    ) =>
            {
                return false
            }
            Tk::Eq if d == 0 => return true,
            Tk::Punct if d == 0 && t.text.len() == 2 && t.text.ends_with('=')
                && !matches!(t.text.as_str(), "==" | "!=" | "<=" | ">=") =>
            {
                return true
            }
            _ => {}
        }
    }
    false
}

/// Whether a block header's last token before the colon closes a closure's
/// parameter list, making the block that follows the closure's body.
fn header_ends_in_closure(toks: &[Token]) -> bool {
    let sig: Vec<&Token> = toks.iter().filter(|t| !t.is_comment()).collect();
    let mut i = sig.len();
    if i > 0 && sig[i - 1].kind == Tk::Colon {
        i -= 1;
    }
    if i > 0 && sig[i - 1].is_kw("do") {
        i -= 1;
    }
    i > 0 && sig[i - 1].kind == Tk::Punct && (sig[i - 1].text == "|" || sig[i - 1].text == "||")
}
